### ISSUE TITLE
Interfacing Rust and Python

### ISSUE THREAD

**Issue by ghost** [rust-nyc/meetups#11]
### Talk Title
Snake, meet Crab: Interfacing Rust and Python

### Brief description of the talk
I'll compare and contrast the cpython and pyo3 crates, and walk through two code examples, the first using the pyo3 crate to expose Rust code as a Python class, and the second using cpython to call Python code from within Rust. 

### Short personal bio about yourself
I'm a former physicist turned software engineer.  I mostly code Python for the ad-tech company Mediamath and have using Rust in various side projects for my own amusement.

**Comment by LucioFranco** [comment]
@ddboline1 Hi! This seems really cool!! Are you able to give this talk on Monday? If so I'll add it to the list! Thanks!

**Comment by ghost** [comment]
Yes, I will be able to give it Monday.

**Comment by LucioFranco** [comment]
@ddboline1 awesome thank you! The meetup page has been updated with your talk!

**Comment by LucioFranco** [comment]
Thanks for giving the talk it was awesome!
