### ISSUE TITLE
Rust Wasm / Smithy

### ISSUE THREAD

**Issue by rbalicki2** [rust-nyc/meetups#12]
### Talk Title

Building Front-End Applications Entirely In Rust: A Love Story

### Brief description of the talk

Would you absolutely love to ditch Javascript? Do you think Typescript doesn't go far enough? Do you preemptively simplify the abstractions you use in your front-end code because there's no compiler to guarantee that others implement things correctly?

Well, oh boy, do I have a talk for you!

In this talk, we'll dive into WebAssembly (what it is, what security and portability advantages it has, how browsers parse it, etc.), the tooling around WebAssembly, and then use Smithy and create-smithy-app to build a website using only Rust, before our very eyes!

#### Why Smithy?

[Smithy](https://www.smithy.rs) is a framework for building WebAssembly applications using idiomatic Rust, and without sacrificing the compiler's safety guarantees. [Here's](https://www.smithy.rs/examples/itunes/) an example Smithy app, along with the [source code](https://github.com/rbalicki2/smithy_itunes_search).

### Short personal bio about yourself

I work at Jetty

### Other info

* I haven't decided what app I'll demonstrate building during the talk. Open to suggestions.
* In particular, I probably want to incorporate some sort of library that is associated with "serious computing" or whatnot, and use it "out of the box".

**Comment by LucioFranco** [comment]
@rbalicki2 how long do you think this talk will be? Should we try to fit in a lighting talk or two as well?
