### ISSUE TITLE
Local Native: A Decentralized Cross-platform App Developed with Rust

### ISSUE THREAD

**Issue by yiwang** [rust-nyc/meetups#13]
### Talk Title
Local Native: A Decentralized Cross-platform App Developed with Rust

### Slides
https://rust-nyc-2019.localnative.app

### Video [Remake]
https://youtu.be/Qvhw8ace6KQ

### Brief description of the tak
[Local Native](https://localnative.app) is a decentralized cross-platform tool to save and sync your web bookmark notes in local database without going through any centralized service.

It reuses [rust code](https://gitlab.com/localnative/localnative) for core native modules for browser extension ([Firefox](https://addons.mozilla.org/en-US/firefox/addon/localnative/) and [Chrome](https://chrome.google.com/webstore/detail/local-native/oclkmkeameccmgnajgogjlhdjeaconnb)), desktop (Electron on [macOS](https://gitlab.com/localnative/localnative-release/tree/master/v0.4.0/mac), [GNU/Linux](https://gitlab.com/localnative/localnative-release/tree/master/v0.4.0/gnu-linux)) and mobile ([iOS](https://apps.apple.com/us/app/local-native/id1443968309), [Android](https://play.google.com/store/apps/details?id=app.localnative)).

This talk will overview the [motivation](https://localnative.app/blog/2019/01/04/why-local-native/), [design](https://chuanyan.live/tags/localnative/) and [architecture](https://localnative.app/blog/) of Local Native, walk through the code of integrating rust with various frameworks/languages, demo the app live in action (attempt to share all Yi Wang's web bookmarks about Rust over LAN/WiFi with audience who installed Local Native mobile or desktop app) and Q and A.

### Short personal bio about yourself
Yi Wang is a data engineer at day, and codes Rust at night.

**Comment by LucioFranco** [comment]
@yiwang this sounds like a super cool talk! Are you okay with giving this for the September meetup? That one should happen late September.

**Comment by yiwang** [comment]
@LucioFranco late September is good.

**Comment by yiwang** [comment]
The screen recording for the talk does not work, I may remake one for the same slides when I get a chance later.
Remade the video in my [class](https://hx2019.localnative.app/fall-week-4.html) and added the video link in the description.
