### ISSUE TITLE
Building my startup with Rust

### ISSUE THREAD

**Issue by brndnmtthws** [rust-nyc/meetups#16]
### Talk Title

Building a startup with Rust

### Brief description of the talk

I quit my job 6 months ago to build a new web business--a messaging app--and I decided to build the entire backend with Rust. I'll discuss some of the good and bad parts about the Rust ecosystem, as well as some of the gotchas I encountered along the way.

### Short personal bio about yourself

I've been writing code since I was 12 and this is my 6th startup (1st that I've cofounded). I began using Rust earlier this year. I've also been contributing to open source projects for a number of years, and it's something I'm really passionate about.

I've previously given talks at a number of meetups, conferences, and private events.

**Comment by LucioFranco** [comment]
This sounds awesome! You able to give this at the october meetup?

**Comment by brndnmtthws** [comment]
@LucioFranco Yessir. Just need some notice to make sure everything's prepared :)

**Comment by LucioFranco** [comment]
@brndnmtthws sounds good, I think we are gonna shoot for later in october like 18-28th. I'll let you know once we have the actual date, but I'll lock you in :) Thanks!

**Comment by LucioFranco** [comment]
@brndnmtthws does the 23rd work?

**Comment by brndnmtthws** [comment]
@LucioFranco Yikes, that's actually the one night I have another commitment. Could we do it the 22nd or 24th instead?

**Comment by LucioFranco** [comment]
@brndnmtthws would the 21st work?

**Comment by brndnmtthws** [comment]
@LucioFranco yes that's great!

Btw let me know if you need space, I can probably help with that as well. Either now or in the future.

**Comment by LucioFranco** [comment]
cool we're gonna go ahead with the 21st at mongo!

**Comment by LucioFranco** [comment]
Meetup has been posted
