### ISSUE TITLE
Building a Gameboy Emulator in Rust

### ISSUE THREAD

**Issue by benkonz** [rust-nyc/meetups#17]
### Talk Title

Building a Gameboy Emulator in Rust

### Brief description of the talk

I've programmed a Gameboy Emulator in Rust and found it to be a really fun side-project. The talk would go into detail on how the emulator works, the technical problems I had to overcome,  some of the advantages/disadvantages of using Rust over other languages for this project, and the future of the project. The source code can be found [here](https://github.com/benkonz/gameboy_emulator)

### Short personal bio about yourself

My name is Benjamin Konz, and I am a Data Engineer at [Impact](https://impact.com). By day, I write Scala code to detect ad fraud on the Forensiq team. By night, I try to improve my Gameboy Emulator and work on the [Jeroo](https://jeroo.org/beta) project! Jeroo is a programming learning tool for middle-high school students to help bridge the gap between visual programming and traditional programming languages. It uses OCaml and Typescript to create a brand new programming language learning environment.

**Comment by LucioFranco** [comment]
@benkonz hi! This sounds awesome! Would you be able to give this on the 21st of October?

**Comment by benkonz** [comment]
@LucioFranco Yeah, that works for me! Is there a time/place for that meetup?

**Comment by softprops** [comment]
I wish I could ❤️ this twice. This would be amazing!

**Comment by LucioFranco** [comment]
@benkonz we're gonna do 21st at the mongodb office.

**Comment by LucioFranco** [comment]
meetup has been posted

**Comment by benkonz** [comment]
@LucioFranco How long should the talk be?

**Comment by LucioFranco** [comment]
30-45min works, I am planning on having two lighting talks so that means well be done around 9 and it should be good.

**Comment by benkonz** [comment]
The slides from my presentation are here: https://docs.google.com/presentation/d/1htoURQiSLG-c3EXlSgD1qO4U2srZfpGNemXpM46Naq8/edit?usp=sharing

**Comment by softprops** [comment]
I think you might need to adjust the share settings on that to anyone with a link can view

**Comment by benkonz** [comment]
@softprops Whoops, my bad. Try this link: https://docs.google.com/presentation/d/1htoURQiSLG-c3EXlSgD1qO4U2srZfpGNemXpM46Naq8/edit?usp=sharing
