### ISSUE TITLE
Future events?

### ISSUE THREAD

**Issue by benkonz** [rust-nyc/meetups#20]
Hi Rust-NYC!

I was wondering if there were any plans on re-starting the RustNYC meetups. I had a lot of fun meeting everyone pre-pandemic, and was wondering if there were plans on continuing the meetups online. 

Thanks,
Ben

**Comment by LucioFranco** [comment]
We had some plans but its been a bit hard coordinating it, we would love to get some help if you're interested :)

**Comment by benkonz** [comment]
Hi @LucioFranco , happy to help. What do you need help with?

**Comment by LucioFranco** [comment]
@benkonz we need someone to take charge on organizing the virtual version, mostly I have not had much time. If you're interested you can shoot me an email at luciofranco14@gmail.com and we can chat a bit further :)
