### ISSUE TITLE
Raw SIMD in Rust, some simple examples and benchmarks

### ISSUE THREAD

**Issue by oconnor663** [rust-nyc/meetups#5]
### Raw SIMD in Rust, some simple examples and benchmarks

Rust has had stable support for many SIMD intrinsics on x86 since version 1.27, with support for further instruction set extensions (AVX512) and other architectures (ARM NEON) coming in the future. We'll look at some simple examples of how to use these intrinsics, and benchmarks to see how much they speed up our code. We'll also use godbolt.org to look at how different implementations generate different assembly code.

Jack has been working on side projects in Rust for several years, particularly the Bao project (https://github.com/oconnor663/bao). Previously he was an engineer at Keybase.

Edit: And here's the code from the talk: https://github.com/oconnor663/simd_examples

**Comment by gj** [comment]
This sounds awesome.

**Comment by softprops** [comment]
this looks great I'll put you down for next week

**Comment by oconnor663** [comment]
Sweet :)

**Comment by oconnor663** [comment]
The code examples I'm going to use tonight are here: https://github.com/oconnor663/simd_examples
